import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './styles/reset.scss'
import './styles/global.scss'
import Sidebar from '@/widgets/Sidebar/ui/Sidebar'
import Header from '@/widgets/Header/ui/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Header />
				<div className='main-container'>
					<Sidebar />
					{children}
				</div>
			</body>
		</html>
	)
}
